output_a="{:d}".format(52)
output_b="{:5d}".format(52)
output_c="{:10d}".format(52)
output_d="{:05d}".format(52)
output_e="{:05d}".format(52)
print(output_a)
print(output_b)
print(output_c)
print(output_d)
print(output_e)

